apiVersion: nvidia.com/v1beta1
kind: DynamoGraphDeployment
metadata:
  name: dsv4-quickstart-dgd
  namespace: dynamo-system
spec:
  components:
    - name: Frontend
      type: frontend
      replicas: 1
      podTemplate:
        spec:
          volumes:
            - name: dsv4-model-cache
              persistentVolumeClaim:
                claimName: dsv4-model-cache
          containers:
            - command:
                - python3
                - "-m"
                - dynamo.frontend
              args:
                - "--model-name"
                - deepseek-ai/DeepSeek-V4-Flash
                - "--model-path"
                - "/home/dynamo/.cache/huggingface/models--deepseek-ai--DeepSeek-V4-Flash/snapshots/6976c7ff1b30a1b2cb7805021b8ba4684041f136"
              image: cr.yichang.puhui.chengfengerlai.com/nvcr.io/nvidia/ai-dynamo/vllm-runtime:1.2.0-deepseek-v4-cuda13-dev.3
              env:
                - name: HF_HOME
                  value: "/home/dynamo/.cache/huggingface"
                - name: HF_ENDPOINT
                  value: https://hf-mirror.com
              name: main
              envFrom:
                - secretRef:
                    name: hf-token-secret
              volumeMounts:
                - name: dsv4-model-cache
                  mountPath: "/home/dynamo/.cache/huggingface"
    - name: VllmDecodeWorker
      type: worker
      replicas: 1
      podTemplate:
        spec:
          volumes:
            - name: dsv4-model-cache
              persistentVolumeClaim:
                claimName: dsv4-model-cache
          containers:
            - command:
                - python3
                - "-m"
                - dynamo.vllm
              args:
                - "--tensor-parallel-size"
                - '8'
                - "--pipeline-parallel-size"
                - '1'
                - "--data-parallel-size"
                - '1'
                - "--kv-cache-dtype"
                - fp8
                - "--max-model-len"
                - '6500'
                - "--max-num-seqs"
                - '512'
                - "--max-num-batched-tokens"
                - '6012'
                - "--model"
                - "/home/dynamo/.cache/huggingface/models--deepseek-ai--DeepSeek-V4-Flash/snapshots/6976c7ff1b30a1b2cb7805021b8ba4684041f136"
                - "--served-model-name"
                - deepseek-ai/DeepSeek-V4-Flash
              image: cr.yichang.puhui.chengfengerlai.com/nvcr.io/nvidia/ai-dynamo/vllm-runtime:1.2.0-deepseek-v4-cuda13-dev.3
              workingDir: "/workspace/examples/backends/vllm"
              env:
                - name: HF_HOME
                  value: "/home/dynamo/.cache/huggingface"
                - name: HF_ENDPOINT
                  value: https://hf-mirror.com
              name: main
              envFrom:
                - secretRef:
                    name: hf-token-secret
              resources:
                limits:
                  nvidia.com/gpu: '8'
                requests:
                  ephemeral-storage: 2Gi
                  nvidia.com/gpu: '8'
              volumeMounts:
                - name: dsv4-model-cache
                  mountPath: "/home/dynamo/.cache/huggingface"
