apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: dsv4-quickstart-dgd
  namespace: dynamo-system
spec:
  pvcs:
    - create: false
      name: dsv4-model-cache
      size: "0"
  services:
    Frontend:
      componentType: frontend
      envFromSecret: hf-token-secret
      replicas: 1
      extraPodSpec:
        mainContainer:
          command:
            - python3
            - -m
            - dynamo.frontend
          args:
            - --model-name
            - deepseek-ai/DeepSeek-V4-Flash
            - --model-path
            - /home/dynamo/.cache/huggingface/models--deepseek-ai--DeepSeek-V4-Flash/snapshots/6976c7ff1b30a1b2cb7805021b8ba4684041f136
          image: cr.internal.puhui.chengfengerlai.com/nvcr.io/nvidia/ai-dynamo/vllm-runtime:1.2.0-deepseek-v4-cuda13-dev.3
          env:
            - name: HF_HOME
              value: /home/dynamo/.cache/huggingface
            - name: HF_ENDPOINT
              value: https://hf-mirror.com
      volumeMounts:
        - mountPoint: /home/dynamo/.cache/huggingface
          name: dsv4-model-cache
    VllmDecodeWorker:
      componentType: worker
      envFromSecret: hf-token-secret
      replicas: 1
      resources:
        limits:
          gpu: "8"
        requests:
          custom:
            ephemeral-storage: 2Gi
          gpu: "8"
      extraPodSpec:
        mainContainer:
          command:
            - python3
            - -m
            - dynamo.vllm
          args:
            - --tensor-parallel-size
            - "8"
            - --pipeline-parallel-size
            - "1"
            - --data-parallel-size
            - "1"
            - --kv-cache-dtype
            - fp8
            - --max-model-len
            - "6500"
            - --max-num-seqs
            - "512"
            - --max-num-batched-tokens
            - "6012"
            - --model
            - /home/dynamo/.cache/huggingface/models--deepseek-ai--DeepSeek-V4-Flash/snapshots/6976c7ff1b30a1b2cb7805021b8ba4684041f136
            - --served-model-name
            - deepseek-ai/DeepSeek-V4-Flash
          image: cr.internal.puhui.chengfengerlai.com/nvcr.io/nvidia/ai-dynamo/vllm-runtime:1.2.0-deepseek-v4-cuda13-dev.3
          workingDir: /workspace/examples/backends/vllm
          env:
            - name: HF_HOME
              value: /home/dynamo/.cache/huggingface
            - name: HF_ENDPOINT
              value: https://hf-mirror.com
      volumeMounts:
        - mountPoint: /home/dynamo/.cache/huggingface
          name: dsv4-model-cache
