imagePullSecrets: []
maintenance-operator-chart:
  operator:
    admissionController:
      certificates:
        certManager:
          enable: false
          generateSelfSigned: false
        custom:
          enable: false
        secretNames:
          operator: maintenance-webhook-cert
      enable: false
    image:
      name: maintenance-operator
      repository: cr.internal.puhui.chengfengerlai.com/nvcr.io/nvidia/mellanox
      tag: network-operator-v26.1.0
  operatorConfig:
    deploy: false
maintenanceOperator:
  enabled: false
nfd:
  deployNodeFeatureRules: true
  enabled: true
node-feature-discovery:
  enableNodeFeatureApi: true
  featureGates:
    NodeFeatureAPI: true
  fullnameOverride: ''
  gc:
    affinity: {}
    annotations: {}
    deploymentAnnotations: {}
    dnsPolicy: ClusterFirstWithHostNet
    enable: true
    extraArgs: []
    extraEnvs: []
    hostNetwork: false
    hostUsers: null
    interval: 1h
    labels: {}
    livenessProbe:
      initialDelaySeconds: 10
    networkPolicy:
      egress:
        - ports:
            - port: 80
              protocol: TCP
            - port: 443
              protocol: TCP
            - port: 53
              protocol: TCP
            - port: 53
              protocol: UDP
            - port: 6443
              protocol: TCP
      enabled: false
      ingress:
        - ports:
            - port: http
              protocol: TCP
    nodeSelector: {}
    podDisruptionBudget:
      enable: false
      minAvailable: 1
      unhealthyPodEvictionPolicy: AlwaysAllow
    podSecurityContext: {}
    port: 8080
    rbac:
      create: true
    readinessProbe:
      initialDelaySeconds: 5
    replicaCount: 1
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 128Mi
    revisionHistoryLimit: null
    serviceAccount:
      annotations: {}
      create: false
      name: node-feature-discovery
    tolerations: []
  global:
    imagePullSecrets: []
  image:
    pullPolicy: IfNotPresent
    repository: >-
      cr.internal.puhui.chengfengerlai.com/nvcr.io/nvidia/mellanox/node-feature-discovery
    tag: network-operator-v26.1.0
  imagePullSecrets: []
  master:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: In
                  values:
                    - ''
            weight: 1
    annotations: {}
    config:
      extraLabelNs:
        - nvidia.com
    denyLabelNs: []
    deploymentAnnotations: {}
    dnsPolicy: ClusterFirstWithHostNet
    enable: true
    enableTaints: false
    extraArgs: []
    extraEnvs: []
    extraLabelNs: []
    hostNetwork: false
    hostUsers: null
    instance: null
    labels: {}
    livenessProbe: {}
    networkPolicy:
      egress:
        - ports:
            - port: 80
              protocol: TCP
            - port: 443
              protocol: TCP
            - port: 53
              protocol: TCP
            - port: 53
              protocol: UDP
            - port: 6443
              protocol: TCP
      enabled: false
      ingress:
        - ports:
            - port: http
              protocol: TCP
    nfdApiParallelism: null
    nodeSelector: {}
    podDisruptionBudget:
      enable: false
      minAvailable: 1
      unhealthyPodEvictionPolicy: AlwaysAllow
    podSecurityContext: {}
    port: 8080
    rbac:
      create: true
    readinessProbe:
      failureThreshold: 10
    replicaCount: 1
    resources:
      limits:
        memory: 4Gi
      requests:
        cpu: 100m
        memory: 128Mi
    resyncPeriod: null
    revisionHistoryLimit: null
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
    serviceAccount:
      annotations: {}
      create: true
      name: node-feature-discovery
    startupProbe:
      failureThreshold: 30
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Equal
        value: ''
  nameOverride: ''
  namespaceOverride: ''
  postDeleteCleanup: false
  priorityClassName: ''
  prometheus:
    enable: false
    labels: {}
    scrapeInterval: 10s
  topologyUpdater:
    affinity: {}
    annotations: {}
    createCRDs: false
    daemonsetAnnotations: {}
    dnsPolicy: ClusterFirstWithHostNet
    enable: false
    extraArgs: []
    extraEnvs: []
    hostNetwork: false
    kubeletStateDir: /var/lib/kubelet
    labels: {}
    livenessProbe:
      initialDelaySeconds: 10
    networkPolicy:
      egress:
        - ports:
            - port: 80
              protocol: TCP
            - port: 443
              protocol: TCP
            - port: 53
              protocol: TCP
            - port: 53
              protocol: UDP
            - port: 6443
              protocol: TCP
      enabled: false
      ingress:
        - ports:
            - port: http
              protocol: TCP
    nodeSelector: {}
    podSecurityContext: {}
    podSetFingerprint: true
    port: 8080
    rbac:
      create: true
    readinessProbe:
      failureThreshold: 10
      initialDelaySeconds: 5
    resources:
      limits:
        memory: 60Mi
      requests:
        cpu: 50m
        memory: 40Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsUser: 0
    serviceAccount:
      annotations: {}
      create: true
    tolerations: []
    updateInterval: 60s
    watchNamespace: '*'
  worker:
    affinity: {}
    annotations: {}
    config:
      sources:
        pci:
          deviceClassWhitelist:
            - '0300'
            - '0302'
          deviceLabelFields:
            - vendor
    daemonsetAnnotations: {}
    dnsPolicy: ClusterFirstWithHostNet
    enable: true
    extraArgs: []
    extraEnvs: []
    hostNetwork: false
    hostUsers: null
    labels: {}
    livenessProbe:
      initialDelaySeconds: 10
    mountUsrSrc: false
    networkPolicy:
      egress:
        - ports:
            - port: 80
              protocol: TCP
            - port: 443
              protocol: TCP
            - port: 53
              protocol: TCP
            - port: 53
              protocol: UDP
            - port: 6443
              protocol: TCP
      enabled: false
      ingress:
        - ports:
            - port: http
              protocol: TCP
    nodeSelector: {}
    podSecurityContext: {}
    port: 8080
    priorityClassName: null
    rbac:
      create: true
    readinessProbe:
      failureThreshold: 10
      initialDelaySeconds: 5
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 5m
        memory: 64Mi
    revisionHistoryLimit: null
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
    serviceAccount:
      annotations: {}
      create: false
      name: node-feature-discovery
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
    updateStrategy: {}
operator:
  admissionController:
    enabled: false
    useCertManager: true
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: In
                values:
                  - ''
          weight: 1
        - preference:
            matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: In
                values:
                  - ''
          weight: 1
  cniBinDirectory: /opt/cni/bin
  cniNetworkDirectory: /etc/cni/net.d
  fullnameOverride: ''
  image: network-operator
  maintenanceOperator:
    drainControllerRequestorID: nvidia.network-operator-drain-controller
    nodeMaintenanceNamePrefix: network-operator
    nodeMaintenanceNamespace: default
    requestorID: nvidia.network-operator-driver-upgrade-controller
    useDrainControllerRequestor: false
    useRequestor: false
  nameOverride: ''
  nodeSelector: {}
  ofedDriver:
    initContainer:
      enable: false
      image: network-operator-init-container
      repository: cr.internal.puhui.chengfengerlai.com/nvcr.io/nvidia/mellanox
      version: network-operator-v26.1.0
  repository: cr.internal.puhui.chengfengerlai.com/nvcr.io/nvidia/cloud-native
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 5m
      memory: 64Mi
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      operator: Equal
      value: ''
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
      operator: Equal
      value: ''
  useDTK: true
sriov-network-operator:
  extraDeploy: []
  global: {}
  imagePullSecrets: []
  images:
    ibSriovCni: >-
      cr.internal.puhui.chengfengerlai.com/nvcr.io/nvidia/mellanox/ib-sriov-cni:network-operator-v26.1.0
    metricsExporter: ghcr.io/k8snetworkplumbingwg/sriov-network-metrics-exporter
    metricsExporterKubeRbacProxy: gcr.io/kubebuilder/kube-rbac-proxy:v0.15.0
    operator: >-
      cr.internal.puhui.chengfengerlai.com/nvcr.io/nvidia/mellanox/sriov-network-operator:network-operator-v26.1.0
    ovsCni: >-
      cr.internal.puhui.chengfengerlai.com/nvcr.io/nvidia/mellanox/ovs-cni-plugin:network-operator-v26.1.0
    rdmaCni: >-
      cr.internal.puhui.chengfengerlai.com/nvcr.io/nvidia/mellanox/rdma-cni:network-operator-v26.1.0
    resourcesInjector: >-
      cr.internal.puhui.chengfengerlai.com/ghcr.io/k8snetworkplumbingwg/network-resources-injector:v1.7.0
    sriovCni: >-
      cr.internal.puhui.chengfengerlai.com/nvcr.io/nvidia/mellanox/sriov-cni:network-operator-v26.1.0
    sriovConfigDaemon: >-
      cr.internal.puhui.chengfengerlai.com/nvcr.io/nvidia/mellanox/sriov-network-operator-config-daemon:network-operator-v26.1.0
    sriovDevicePlugin: >-
      cr.internal.puhui.chengfengerlai.com/nvcr.io/nvidia/mellanox/sriov-network-device-plugin:network-operator-v26.1.0
    webhook: >-
      cr.internal.puhui.chengfengerlai.com/nvcr.io/nvidia/mellanox/sriov-network-operator-webhook:network-operator-v26.1.0
  operator:
    admissionControllers:
      certificates:
        certManager:
          enabled: true
          generateSelfSigned: true
        custom:
          enabled: false
        secretNames:
          injector: network-resources-injector-cert
          operator: operator-webhook-cert
      enabled: false
      networkPolicy:
        injector:
          port: '6443'
        operator:
          port: '6443'
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
                - key: node-role.kubernetes.io/master
                  operator: In
                  values:
                    - ''
            weight: 1
          - preference:
              matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: In
                  values:
                    - ''
            weight: 1
    clusterType: kubernetes
    cniBinPath: /opt/cni/bin
    externalDrainer:
      enabled: false
    extraEnv: {}
    fullnameOverride: ''
    metricsExporter:
      certificates:
        secretName: metrics-exporter-cert
      port: '9110'
      prometheusOperator:
        deployRules: false
        enabled: false
        namespace: monitoring
        serviceAccount: prometheus-k8s
    nameOverride: ''
    nodeSelector: {}
    resourcePrefix: nvidia.com
    staleNodeStateCleanupDelayMinutes: '30'
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
  sriovOperatorConfig:
    configDaemonEnvVars: {}
    configDaemonNodeSelector:
      beta.kubernetes.io/os: linux
      network.nvidia.com/operator.mofed.wait: 'false'
    configurationMode: daemon
    deploy: false
