apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dcgm-exporter-monitor
  namespace: gpu-operator # 替换为 dcgm-exporter 所在的命名空间
  labels:
    release: kube-prometheus-stack # 确保这个 label 与你的 Prometheus 实例的选择器匹配
spec:
  selector:
    matchLabels:
      app: nvidia-dcgm-exporter # 确保匹配 dcgm-exporter 的 Service 标签
  endpoints:
  - port: gpu-metrics # Service 配置文件中定义的端口名称
    interval: 15s